### ISSUE TITLE
Необходимо протестить фичу с %userName%

### ISSUE THREAD

**Issue by infoniten** [infoniten/ITsubbotnik_telegram_bot_20019#10]
Прикрутил фичу, теперь после команды /start бот обращается к пользователю по имени.

Необходимо проверить что бы у всех она работала корректно.

**Comment by onixe** [comment]
Фича с именем работает.
Бот задает один вопрос и молчит после получения ответа.
Программа останавливается на 
public final native void wait(long var1) throws InterruptedException;

**Comment by infoniten** [comment]
Хотфиксом исправлен описанный баг, протестил фичу на друзьях, у них тоже всё работает.
